# Task 1: Understanding Dataset & Data Types
## Dataset 1: Titanic Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Titanic dataset
df = pd.read_csv('titanic.csv')
# Display first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# Display last 5 rows
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas",female,14.0,1,0,237736,30.0708,NaN,C

In [4]:
# Information about columns, data types, and null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  10 non-null     int64
 1   Survived     10 non-null     int64
 2   Pclass       10 non-null     int64
 3   Name         10 non-null     object
 4   Sex          10 non-null     object
 5   Age          9 non-null      float64
 6   SibSp        10 non-null     int64
 7   Parch        10 non-null     int64
 8   Ticket       10 non-null     object
 9   Fare         10 non-null     float64
 10  Cabin        3 non-null      object
 11  Embarked     10 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 1.1+ KB

In [5]:
# Statistical summary of numerical columns
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,10.00000,10.000000,10.000000,9.000000,10.000000,10.000000,10.000000
mean,5.50000,0.500000,2.300000,28.111111,0.700000,0.300000,27.020820
std,3.02765,0.527046,0.948683,14.945271,0.948683,0.674949,23.601938
min,1.00000,0.000000,1.000000,2.000000,0.000000,0.000000,7.250000
25%,3.25000,0.000000,1.250000,22.000000,0.000000,0.000000,8.152075
50%,5.50000,0.500000,3.000000,27.000000,0.500000,0.000000,16.104150
75%,7.75000,1.000000,3.000000,35.000000,1.000000,0.000000,46.414575
max,10.00000,1.000000,3.000000,54.000000,3.000000,2.000000,71.283300

In [6]:
# Count missing values in each column\n"
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            1
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          7
Embarked       0
dtype: int64

In [7]:
# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=['int64','float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns
numerical_cols, categorical_cols

(Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object'),
 Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object'))

In [8]:
# Unique values in categorical columns
for col in categorical_cols:
    print(col, df[col].unique())

Name ['Braund, Mr. Owen Harris' 'Cumings, Mrs. John Bradley'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard' 'Johnson, Mrs. Oscar W'
 'Nasser, Mrs. Nicholas']
Sex ['male' 'female']
Ticket ['A/5 21171' 'PC 17599' 'STON/O2. 3101282' '113803' '373450' '330877'
 '17463' '349909' '347742' '237736']
Cabin [nan 'C85' 'C123' 'E46']
Embarked ['S' 'C' 'Q']

## Dataset 2: Students Performance Dataset

In [11]:
# Load StudentPerformance dataset
students_df = pd.read_csv('StudentsPerformance.csv')
# Display first 5 rows
students_df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group A,bachelor's degree,standard,none,72,72,74
1,male,group B,some college,free/reduced,completed,69,90,88
2,female,group C,master's degree,standard,none,90,95,93
3,male,group A,high school,standard,completed,47,57,44
4,female,group B,associate's degree,free/reduced,none,76,78,75

In [12]:
# Display last 5 rows
students_df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,high school,standard,completed,47,57,44
4,female,group B,associate's degree,free/reduced,none,76,78,75
5,male,group C,some college,standard,completed,71,74,70
6,female,group A,high school,standard,none,88,89,90
7,male,group B,bachelor's degree,free/reduced,completed,64,67,65

In [13]:
# Information about columns, data types, and null values
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       8 non-null      object
 1   race/ethnicity               8 non-null      object
 2   parental level of education  8 non-null      object
 3   lunch                        8 non-null      object
 4   test preparation course      8 non-null      object
 5   math score                   8 non-null      int64
 6   reading score                8 non-null      int64
 7   writing score                8 non-null      int64
dtypes: int64(3), object(5)
memory usage: 644.0+ bytes

In [14]:
# Statistical summary of numerical columns
students_df.describe()

       math score  reading score  writing score
count    8.000000       8.000000       8.000000
mean    72.125000      77.750000      74.875000
std     13.600814      12.914554      16.057375
min     47.000000      57.000000      44.000000
25%     67.750000      70.750000      68.750000
50%     71.500000      76.000000      74.500000
75%     79.000000      89.250000      88.500000
max     90.000000      95.000000      93.000000

In [15]:
# Count missing values in each column\n"
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            1
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          7
Embarked       0
dtype: int64

In [16]:
# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=['int64','float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns
numerical_cols, categorical_cols

(Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object'),
 Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object'))

In [17]:
# Unique values in categorical columns
for col in categorical_cols:
    print(col, df[col].unique())

Name ['Braund, Mr. Owen Harris' 'Cumings, Mrs. John Bradley'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard' 'Johnson, Mrs. Oscar W'
 'Nasser, Mrs. Nicholas']
Sex ['male' 'female']
Ticket ['A/5 21171' 'PC 17599' 'STON/O2. 3101282' '113803' '373450' '330877'
 '17463' '349909' '347742' '237736']
Cabin [nan 'C85' 'C123' 'E46']
Embarked ['S' 'C' 'Q']

### Final Observations
- Both datasets contain numerical and categorical features
- Titanic dataset target variable: Survived
- Students dataset targets: Math, Reading, Writing scores
- Both datasets are suitable for Machine Learning after preprocessing